remote_theme: just-the-docs/just-the-docs
color_scheme: dark
#remote_theme: pages-themes/minimal@v0.2.0

title: TestPage
description: Learning how github pages work
repository: wiggledgrin/testpage

# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Automatic Room Correction
    link                                  : docs/help/additional.html
    description                           : Generate parametric equalizer settings and export to supported hardware.

  - title                                 : Subwoofer Phase
    description                           : Set subwoofer phase with confidence using magnitude and/or phase based tuning approaches.
    link                                  : docs/help/additional.html

  - title                                 : Crossover selection
    description                           : Avoid the guesswork.  Measure how individual elements perform an choose the right crossover point.
    link                                  : docs/help/additional.html

  - title                                 : Sine Sweep Measurements
    description                           : HouseCurve automatically checks measurements and discards when quality is too low.
    link                                  : docs/help/additional.html

  - title                                 : Documentation
    description                           : HouseCurve comes with extensive documentation on measuring audio systems and step-by-step tuning advice.
    link                                  : docs/help/additional.html


