remote_theme: just-the-docs/just-the-docs
color_scheme: dark
#remote_theme: pages-themes/minimal@v0.2.0

title: TestPage
description: Learning how github pages work
repository: wiggledgrin/testpage

# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : GitHub Pages Jekyll Theme
    description                           : Designed for GitHub Pages. Fork. Edit _config.yml.
    fontawesome_icon_name                 : magic

  - title                                 : iPhone Device Preview
    description                           : Preview your app in the context of an iPhone device.
    fontawesome_icon_name                 : mobile

  - title                                 : Video Support
    description                           : Preview app video on the iPhone device simply by
    fontawesome_icon_name                 : play-circle

  - title                                 : Automatic Icon and Metadata
    description                           : Enter iOS app ID in the _config.yml file to automatically
    fontawesome_icon_name                 : sync

  - title                                 : Easy to Tweak
    description                           : Tweak accent color, images, icons and transparency via
    fontawesome_icon_name                 : adjust


